#!/bin/bash
#
# About: Auto Update
# Author: liberodark
# Thanks :
# License: GNU GPLv3

version="0.0.8"

echo "Welcome on Auto Update Script $version"

#=================================================
# CHECK ROOT
#=================================================

if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root" ; exit 1 ; fi

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST AND VAR
#=================================================

distribution=$(cat /etc/*release | grep "PRETTY_NAME" | sed 's/PRETTY_NAME=//g' | sed 's/["]//g' | awk '{print $1}')

update="/usr/bin/check_updates"
yum_conf="/etc/yum.repos.d/CentOS-Base.repo"
yum_fastestmirror="/etc/yum/pluginconf.d/fastestmirror.conf"
date=$(date +%Y.%m.%d_%H-%M-%S)
dest="/root/.backup-repo"
lock="/tmp/auto-update.lock"

exec 9>"${lock}"
flock -n 9 || exit

detect_update(){
if [ ! -f "$update" ]; then
echo "Error check_updates is not installed correctly"
ln -s /usr/local/nagios/libexec/check_updates /usr/bin/check_updates
fi
}

detect_yum_fastestmirror(){
if [ -f "$yum_fastestmirror" ]; then
sed -i "s@enabled=1@enabled=0@g" /etc/yum/pluginconf.d/fastestmirror.conf
fi
}

detect_yum_repo(){
if [ -f "$yum_conf" ]; then
echo "Error Yum configuration already is installed"
mkdir -p "$dest"
cp -a /etc/yum.repos.d "$dest"/"$date"
cd /etc/yum.repos.d/ || exit
rm -f $(ls -I "myrepo.repo" )
fi
}

stop_service(){
systemctl stop nrpe > /dev/null 2>&1
systemctl stop docker > /dev/null 2>&1
systemctl stop dockerd > /dev/null 2>&1
systemctl stop httpd > /dev/null 2>&1
systemctl stop nginx > /dev/null 2>&1
systemctl stop apache2 > /dev/null 2>&1
systemctl stop tomcat > /dev/null 2>&1
systemctl stop mariadb > /dev/null 2>&1
systemctl stop mysql > /dev/null 2>&1
systemctl stop mysqld > /dev/null 2>&1
systemctl stop postgres > /dev/null 2>&1
}

fix_cache(){
systemctl stop packagekit
sed -i "s@#KeepCache=false@KeepCache=false@g" /etc/PackageKit/PackageKit.conf
systemctl start packagekit
}

pkcon_refresh(){
rm -rf /var/cache/PackageKit
pkcon refresh force -c -1 > /dev/null 2>&1
}

make_update(){
if [ "$distribution" = "CentOS" ] || [ "$distribution" = "Red\ Hat" ] || [ "$distribution" = "Oracle" ]; then
  detect_update || exit
  detect_yum_repo || exit
  detect_yum_fastestmirror || exit
  stop_service
  fix_cache || exit
  pkcon_refresh || exit
  check_updates -lock /tmp/check_updates.lock -update -y
  echo "Update Finish : System wheel reboot in 2 mins !!!"
  sleep 2m && reboot
      
elif [ "$distribution" = "Fedora" ]; then
  detect_update || exit
  stop_service
  fix_cache || exit
  pkcon_refresh || exit
  check_updates -lock /tmp/check_updates.lock -update -y
  echo "Update Finish : System wheel reboot in 2 mins !!!"
  sleep 2m && reboot
    
elif [ "$distribution" = "Debian" ] || [ "$distribution" = "Raspbian" ] || [ "$distribution" = "Ubuntu" ] || [ "$distribution" = "Deepin" ]; then
  detect_update || exit
  stop_service
  fix_cache || exit
  pkcon_refresh || exit
  check_updates -lock /tmp/check_updates.lock -update -y
  echo "Update Finish : System wheel reboot in 2 mins !!!"
  sleep 2m && reboot
fi
}

make_update || exit
