#!/bin/bash
#
# About: Auto Update
# Author: liberodark
# Thanks :
# License: GNU GPLv3

version="0.0.1"

echo "Welcome on Auto Update Script $version"

#=================================================
# CHECK ROOT
#=================================================

if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root" ; exit 1 ; fi

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST AND VAR
#=================================================

distribution=$(cat /etc/*release | grep "PRETTY_NAME" | sed 's/PRETTY_NAME=//g' | sed 's/["]//g' | awk '{print $1}')

update=/usr/bin/check_updates
yum_conf=/etc/yum.repos.d/
temp=$(mktemp)

if [ -e "$update" ]; then
echo "Error check_updates is not installed correctly"
ln -s /usr/local/nagios/libexec/check_updates /usr/bin/check_updates
fi

if [ -e "$yum_conf" ]; then
echo "Error Yum configuration already is installed"
mv /etc/yum.repos.d/* "$temp"
cd /etc/yum.repos.d/ || exit
wget http://10.17.32.24/repo/repo.tar.gz
tar -xvf repo.tar.gz && rm -f repo.tar.gz
fi

check_updates -lock /tmp/check_updates.lock -update -y